### ISSUE TITLE
Motion not resetting

### ISSUE THREAD

**Issue by yannip1234** [Tommrodrigues/homebridge-web-motion#1]
Great plugin so far! However, the motion sensor is not resetting after being triggered. Here is my config snippet. My motion sensor sends a post request to http://IPADDRESS:2000/crv/motionDetected/1 only when motion is detected. It is constantly polling script. I have no idea what is wrong! Thanks.

`{
            "platform": "WebMotion",
            "sensors": [
                {
                    "name": "CR-V Sensor",
                    "id": "crv",
                    "port": 2000,
                    "autoReset": true,
                    "autoResetDelay": 60
                },
                {
                    "name": "Odyssey Sensor",
                    "id": "odyssey",
                    "port": 2000,
                    "autoReset": true,
                    "autoResetDelay": 60
                }
            ]
        }`

**Comment by RomanGz** [comment]
The reset configs need to go under the global platform config.

```
{
    "platform": "WebMotion",
    "autoReset": true,
    "autoResetDelay": 5,
    "sensors": []
}

**Comment by phenotypic** [comment]
Hi @yannip1234, @RomanGz's response is the correct implementation for the reset configurations. Following the example they provided should solve your issue.
