### ISSUE TITLE
autoReset and autoReset for individual sensors

### ISSUE THREAD

**Issue by teymur1988** [Tommrodrigues/homebridge-web-motion#2]
Hi there,

Very useful plugin, thank you! Would it be possible to make the autoreset and autoreset delay functions available for individual sensors? I’m using 2 sensors with this plugin, and want to have diffrent autoresetdelay values for each sensor. would it be possible to look at?

thank you

**Comment by phenotypic** [comment]
Hi @teymur1988, apologies for taking so long to respond to your issue.

I agree that having individual `autoReset` and `autoResetDelay` fields for each sensor would be useful.

Unfortunately, as I do not use this plugin myself anymore, it is a bit trickier for me to test real-world implementation of changes. I also don't have the spare time to experiment with it manually at the moment.

Please feel free to fork this plugin and make the necessary changes, then I'd be happy to check over the changes in a pull request before merging. If not, this is something I may look into sometime in the future.
